spring.application.name=demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${BACKEND_DB_URL}
spring.datasource.username=ProiectPS
spring.datasource.password=${BACKEND_DB_PASS}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

