server.port=8082
spring.application.name=NotificationMicroservice

spring.datasource.url=${MICRO_DB_URL}
spring.datasource.username=${MICRO_DB_USER}
spring.datasource.password=${MICRO_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=floria.razvan14@gmail.com
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

twilio.account-sid=${TWILIO_SID}
twilio.auth-token=${TWILIO_TOKEN}
twilio.phone-number=+19015578610